apiVersion: v1
kind: Service
metadata:
  labels:
    name: livescore-demo-vertx-amqp-bridge-rest-style
    project: live-score-demo
  name: livescore-demo-vertx-amqp-bridge-rest-style
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
  selector:
    name: livescore-demo-vertx-amqp-bridge-rest-style
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: livescore-demo-vertx-amqp-bridge-rest-style
  labels:
    project: live-score-demo
spec:
  replicas: 1
  template:
    metadata:
      name: livescore-demo-vertx-amqp-bridge-rest-style
      labels:
        name: livescore-demo-vertx-amqp-bridge-rest-style
        project: live-score-demo
    spec:
      containers:
        - image: scholzj/livescore-demo-vertx-amqp-bridge-rest-style:latest
          name: livescore-demo-vertx-amqp-bridge-rest-style
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: livescore-demo-vertx-amqp-bridge-rest-style-config
                  key: vertx.log.level
        - image: scholzj/qpid-dispatch:0.7.0
          name: qpid-dispatch
          imagePullPolicy: Always
          env:
            - name: QDROUTERD_CONFIG_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: livescore-demo-vertx-amqp-bridge-rest-style-config
                  key: dispatch.config
          ports:
            - containerPort: 5672
              name: amqp
